spring:
  datasource:
    url: jdbc:mysql://mysql.railway.internal:3306/student_app
    username: root
    password: ueYeEqyyFfhMpaOvYYdKCNHrpbeLvAqk

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false